<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- WORLD LINK-->
    <link name="world_link">
    
    </link>

    <!-- BASE JOINT-->

    <joint name="base_joint" type="fixed">
        <parent link="world_link"/>
        <child link="base_link"/>
        <origin xyz="1.5 1 0" rpy="0 0 0"/>
    </joint>

    <!-- BASE LINK-->

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0.05"/>
            <geometry>
                <box size="2.5 1.5 0.1"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.05"/>
            <geometry>
                <box size="2.5 1.5 0.1"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="12" x="2.5" y="1.5" z="0.1">
            <origin xyz="0 0 0.05"/>
        </xacro:inertial_box>
    </link>

    <!-- SLIDER JOINT-->

    <joint name="slider_joint" type="prismatic">
        <parent link="base_link"/>
        <child link="slider_link"/>
        <origin xyz="-1.25 0 0.1" rpy="0 0 0"/>
        <limit lower="0" upper="2" velocity="100" effort="100"/>
        <axis xyz="1 0 0"/>
    </joint>

    <!-- SLIDER LINK-->

    <link name="slider_link">
        <visual>
            <geometry>
                <box size="0.5 0.25 0.15"/>
            </geometry>
            <origin xyz="0 0 0.075"/>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.5 0.25 0.15"/>
            </geometry>
            <origin xyz="0 0 0.075"/>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.5" y="0.25" z="0.15">
            <origin xyz="0 0 0.075"/>
        </xacro:inertial_box>
    </link>

    <!-- ARM JOINT-->

    <joint name="arm_joint" type="revolute">
        <parent link="slider_link"/>
        <child link="arm_link"/>
        <origin xyz="0.25 0 0.15" rpy="0 0 0"/>
        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/>
        <axis xyz="0 -1 0"/>
    </joint>

    <!-- ARM LINK-->

    <xacro:property name="arm_length" value="1"/>
    <xacro:property name="arm_radius" value="0.1"/>
    
    <link name="arm_link">
        <visual>
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}"/>
            </geometry>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}"/>
            </geometry>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CAMERA JOINT-->

    <joint name="camera_joint" type="fixed">
        <parent link="arm_link"/>
        <child link="camera_link"/>
        <origin xyz="${arm_length} 0 ${arm_radius + 0.075}" rpy="0 0 0"/>
    </joint>

     <!-- CAMERA LINK-->

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.06 0.15 0.15"/>
            </geometry>
            <origin xyz="0.03 0 0"/>
            <material name="white"/>
        </visual>
        <visual>
            <geometry>
                <cylinder length="0.06" radius="0.04"/>
            </geometry>
            <origin xyz="0.06 0 0" rpy="0 ${pi/2} 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.09 0.15 0.15"/>
            </geometry>
            <origin xyz="0.045 0 0"/>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.09" y="0.15" z="0.15">
            <origin xyz="0.045 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>